<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Will You Be My Valentine?</title>
    <style>
        body {
            font-family: sans-serif;
            background-color: #f8e0ff; /* Light pink/purple background */
            text-align: center;
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            min-height: 100vh;
        }

        h1 {
            color: #e91e63; /* Pink heading */
            font-size: 3em;
            margin-bottom: 20px;
        }

        img {
            max-width: 300px; /* Adjust image size as needed */
            height: auto;
            margin-bottom: 20px;
        }

        p {
            font-size: 1.2em;
            margin-bottom: 30px;
            color: #333; /* Dark gray text */
        }

        .button-container {
          display: flex;
          justify-content: center; /* Center the buttons */
          gap: 20px; /* Space between buttons */
        }

        button {
            background-color: #e91e63; /* Pink button */
            color: white;
            padding: 15px 30px;
            border: none;
            border-radius: 5px;
            font-size: 1.1em;
            cursor: pointer;
            transition: background-color 0.3s ease; /* Smooth hover effect */
        }

        button:hover {
            background-color: #d81b60; /* Darker pink on hover */
        }

         #no-button {
            background-color: #ddd; /* Gray for the "No" button */
        }

        #no-button:hover {
            background-color: #ccc; /* Darker gray on hover */
        }


    </style>
</head>
<body>

    <h1>Will You Be My Valentine?</h1>

    <img src="https://media.tenor.com/PXKZhCEfEfsAAAAj/bubu-bubu-dudu.gif" alt="Valentine's Image">  <p>Hi My cute cute mochi,</p>
    <p>I've been thinking about you, and I'd really love to spend Valentine's Day with you.  Will you be my Valentine?</p>

    <div class="button-container">
        <button id="yes-button">Yes!</button>
        <button id="no-button">No</button>
    </div>

    <script>
      const yesButton = document.getElementById('yes-button');
      const noButton = document.getElementById('no-button');

      yesButton.addEventListener('click', () => {
          alert('YAY! I can\'t wait to spend time with you and do all the things we want to do, I love you my mochi ko!!'); // Or redirect to a thank you page
      });

      noButton.addEventListener('click', () => {
        //  A fun "try again" response, or perhaps a gentle message
          alert('Aww, maybe next time!  But you\'re still awesome.');
      });

    </script>

</body>
</html
